pgadmin:
  container_name: pgadmin_container
  image: dpage/pgadmin4
  environment:
    PGADMIN_DEFAULT_EMAIL: foo@bar.me
    PGADMIN_DEFAULT_PASSWORD: example
  ports:
    - "5050:80"
  restart: unless-stopped